language: ruby
rvm:
- 2.3
script: ./script/cibuild

# branch whitelist
branches:
  except: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - sudo apt-get update && sudo apt-get install libicu-dev
