name: Ivan Tse
tagline: Ruby apprentice learning to code more beautifully
markdown: redcarpet
pygments: true
permalink: :title
emoji_dir: /images/emoji
timezone: America/New_York
excerpt_separator: ""
disqus_shortname: ivantseblog
