source 'https://rubygems.org'
gem 'jekyll', '~> 2.0'
gem 'rake', '~> 10.3'
gem 'nokogiri', '~> 1.6'
gem 'jekyll-html-pipeline'
gem 'rinku'
gem 'gemoji'
gem 'github-markdown'
gem 'github-linguist'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
