source 'https://rubygems.org'
gem 'jekyll', '~> 2.1'
gem 'rake', '~> 10.3'
gem 'nokogiri', '~> 1.6'
gem 'jekyll-html-pipeline'
gem 'rinku'
gem 'gemoji'
gem 'github-markdown'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-git_metadata'
gem 'jekyll-autolink_email'
gem 'html-proofer'
